name: remote_storage
description: A remote storage wrapper to be used across all the apps
version: 1.0.0
# homepage: ''
publish_to: "none"

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  core:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: pkg/core
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  custom_builders:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: builders/custom_builders
  custom_lint: ^0.7.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
