name: my_workspace
packages:
  - pkg/**
  - builders/**
scripts:
  bootstrap:
    run: melos bootstrap

  test:
    run: melos exec -- flutter test
    description: "Run all tests in parallel across all packages"

  test_changed:
    run: melos exec --since=origin/main -- flutter test
    description: "Run tests only for changed packages"

  format:
    run: melos exec -- flutter format --set-exit-if-changed
    description: "Format all packages"

  analyze:
    run: melos exec -- flutter analyze .
    description: "Analyze all packages"

  pub_upgrade:
    run: melos exec -- dart pub upgrade
    description: "Upgrade all packages"

  clean:
    run: melos exec -- flutter clean
    description: "Clean all packages"

  # Build core first so its .g.dart exist, then build rest in dependency order.
  build_runner_build: >
    melos exec --scope=core -- dart run build_runner build -d
    && melos exec --order-dependents -c 1 -- dart run build_runner build -d

  build_runner_clean: melos exec -- dart run build_runner clean

  build_runner_watch: melos exec --order-dependents -- dart run build_runner watch -d
