name: ads
description: A pkg to show ads in the app
version: 1.0.0
# homepage: ''
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  core:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: pkg/core
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_builders:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: builders/custom_builders
  custom_lint: ^0.7.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
