name: Lint & Test

on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Granting access to private organization repos
        id: granting-access-to-private-repos
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.CORE_SSH_PK }}
            ${{ secrets.AXINO_CORE_SSH_PK }}
            ${{ secrets.AUTHENTICATION_SSH_PK }}
            ${{ secrets.CRASHLYTICS_SSH_PK }}
            ${{ secrets.ANALYTICS_SSH_PK }}
            ${{ secrets.REMOTE_STORAGE_SSH_PK }}
            ${{ secrets.REMOTE_CONFIG_SSH_PK }}

      - name: Setup Flutter Env
        id: flutter-setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check Code Format Changes
        id: check-code-format
        run: dart format . --set-exit-if-changed

      - name: Analyze code
        id: analyze-code
        run: |
          flutter pub get
          dart analyze .

      - name: Run flutter tests
        id: running-widget-tests
        run: |
          flutter pub get
          flutter test

      - name: notify slack
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: 'axino-client-pipeline-monitor'
          config: .github/resources/slack.yml
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
