name: core
description: A package that contains core functionality for the projects
version: 1.0.0
# homepage: ''
publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  async: ^2.11.0
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.3.0
  cloud_functions: ^5.1.0
  connectivity_plus: ^6.0.5
  custom_annotations:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: builders/custom_annotations
  dartz: ^0.10.1
  device_info_plus: ^11.3.3
  dio: ^5.6.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  faker: ^2.2.0
  firebase_core: ^3.4.0
  firebase_database: ^11.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_pdfview: ^1.3.4
  flutter_svg: ^2.0.10
  flutter_timezone: ^3.0.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_storage: ^2.1.1
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  pdfrx: ^1.1.1
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  signals: ^5.5.0
  timezone: ^0.9.4
  url_launcher: ^6.3.0
  uuid: ^4.5.0
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_builders:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: builders/custom_builders
  custom_lint: ^0.7.0
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^5.9.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/png/
    - assets/svg/
