include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
  # plugins:
  #   - custom_lint

linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
