name: crashlytics
description: A crashlytics wrapper to be used across all the apps
version: 1.0.0
# homepage: ''
publish_to: "none"

environment:
  sdk: ^3.5.1

dependencies:
  core:
    path: ../core
  firebase_crashlytics: ^4.1.0
  flutter:
    sdk: flutter
  sentry_flutter: ^8.11.2

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  custom_builders:
    path: ../../builders/custom_builders
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
