// This file is generated by Flart plugin.
// Please, do not edit this file.
// ignore_for_file: unnecessary_import
// Last updated: 11/18/2024, 04:00:13 PM

import 'dart:ui';
import 'package:flutter/material.dart';

abstract class AppEffectStyles {
  const AppEffectStyles._();
  static const BoxShadow shadowL1Effect0 = BoxShadow(
    color: Color(0x14000000),
    blurRadius: 2,
  );

  static const BoxShadow shadowL1Effect1 = BoxShadow(
    color: Color(0x14000000),
    offset: Offset(0, 2),
    blurRadius: 4,
  );

  static const BoxShadow shadowL2Effect0 = BoxShadow(
    color: Color(0x14000000),
    blurRadius: 4,
  );

  static const BoxShadow shadowL2Effect1 = BoxShadow(
    color: Color(0x19000000),
    offset: Offset(0, 4),
    blurRadius: 8,
  );
  static const BoxShadow shadowL3Effect0 = BoxShadow(
    color: Color(0x14000000),
    blurRadius: 6,
  );

  static const BoxShadow shadowL3Effect1 = BoxShadow(
    color: Color(0x19000000),
    offset: Offset(0, 8),
    blurRadius: 16,
  );

  static const BoxShadow shadowL4Effect0 = BoxShadow(
    color: Color(0x14000000),
    blurRadius: 8,
  );

  static const BoxShadow shadowL4Effect1 = BoxShadow(
    color: Color(0x19000000),
    offset: Offset(0, 10),
    blurRadius: 20,
  );

  static const BoxShadow shadowL5Effect0 = BoxShadow(
    color: Color(0x14000000),
    blurRadius: 10,
  );

  static const BoxShadow shadowL5Effect1 = BoxShadow(
    color: Color(0x19000000),
    offset: Offset(0, 12),
    blurRadius: 24,
  );

  static const BoxShadow shadowL6Effect0 = BoxShadow(
    color: Color(0x14000000),
    blurRadius: 12,
  );

  static const BoxShadow shadowL6Effect1 = BoxShadow(
    color: Color(0x19000000),
    offset: Offset(0, 16),
    blurRadius: 32,
  );
}
